# Generated by Django 3.1.7 on 2021-03-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_name', models.CharField(max_length=36, verbose_name='Statistika ID')),
                ('name', models.CharField(max_length=6, verbose_name='Qisqa havola')),
                ('url', models.CharField(max_length=1024, verbose_name='Havola')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15, verbose_name='IP manzili')),
                ('referer', models.CharField(blank=True, help_text='Qaysi manzildan kelganligi', max_length=512, null=True, verbose_name='Referal manzili')),
                ('user_agent', models.CharField(max_length=256, verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.url')),
            ],
        ),
    ]
